Update terminal.txt
vim-jp/vimdoc-ja-working pull request #1123
Opened 2022-07-24 15:18 UTC by vampire-yuta

翻訳（というか整形？）をしました！  
レビューよろしくお願いします :smile:

素人質問で恐縮なのですが、この場合のチルダってどういう意味になるのでしょうか 🤔

2022-07-24 23:37 UTC, tsuyoshicho requested changes
@vampire-yuta さん、ありがとうございます。

文末の `~` (チルダ) については `:help help-writing` の列見出しのところを見るとわかりやすいです。
また、実際の表示は `:help terminal.txt@en` として現在の英語版を見てみるのも参考になるでしょう。

説明としてチルダが文末にあると、列の見出しの強調になるのですが
現在はそれにとどまらず、小見出しでのスタイルにも利用されてます(オフィシャルに)

そしてこのチルダですが、末尾にさえあればスタイルは変化するかとは思いますが、英語も日本語でも間にスペースを入れるようにしています。
これは既存の部分を読んでいるとそういうのがあるので、わかるかと思います。

ですので、今回の修正を適用するにあたって、各見出しでスペースが不足していましたので、指摘を行いました。

2022-07-24 23:37 UTC, tsuyoshicho commented on doc/terminal.jax
> +ショートカット~
```suggestion
ショートカット ~
```
指摘は全体コメントにて

2022-07-24 23:37 UTC, tsuyoshicho commented on doc/terminal.jax
> +ポップアップメニュー~
```suggestion
ポップアップメニュー ~
```
同上

2022-07-24 23:37 UTC, tsuyoshicho commented on doc/terminal.jax
> +Vimのウィンドウ幅~
```suggestion
Vimのウィンドウ幅 ~
```
同上

2022-07-25 00:23 UTC, h-east reviewed
@tsuyoshicho さんの指摘がfixされればLGTMです。

2022-07-25 14:56 UTC, vampire-yuta commented
> @vampire-yuta さん、ありがとうございます。
> 
> 文末の `~` (チルダ) については `:help help-writing` の列見出しのところを見るとわかりやすいです。 また、実際の表示は `:help terminal.txt@en` として現在の英語版を見てみるのも参考になるでしょう。
> 
> 説明としてチルダが文末にあると、列の見出しの強調になるのですが 現在はそれにとどまらず、小見出しでのスタイルにも利用されてます(オフィシャルに)
> 
> そしてこのチルダですが、末尾にさえあればスタイルは変化するかとは思いますが、英語も日本語でも間にスペースを入れるようにしています。 これは既存の部分を読んでいるとそういうのがあるので、わかるかと思います。
> 
> ですので、今回の修正を適用するにあたって、各見出しでスペースが不足していましたので、指摘を行いました。
> 
> あと絶対ダメ、というわけではないですが、コミットログがちょっと不明確すぎるので、次回から多少分りやすくしていただければと。

ご丁寧に説明いただきありがとうございます。見出しなんですね 🙏 
ヘルプ見て勉強します！  
スペース不足承知しました。スイマセン。  
コミットログについても承知しました！ありがとうございます！

2022-07-25 14:57 UTC, vampire-yuta commented
レビューありがとうございます！ 
指摘3コメント対応しました！

2022-07-25 22:36 UTC, tsuyoshicho approved these changes

2022-07-25 23:58 UTC, h-east approved these changes

2022-07-25 23:58 UTC, merged

2022-07-25 23:58 UTC, h-east commented
Thanks:+1: