Update filetype.{txt,jax}
vim-jp/vimdoc-ja-working pull request #1138
Opened 2022-09-21 15:31 UTC by ryicoh

2022-09-22 09:55 UTC, tsuyoshicho requested changes

2022-09-22 09:55 UTC, tsuyoshicho commented on doc/filetype.jax
> +れる。これらのグローバル変数は、概念的にはfbcオプションの-forcelangと-langに対
ここの流れとして
「最初に g:freebasic_forcelang で見付かる名前、次に編集しはじめたファイル内のディレクティブもしくはメタコマンド、最終的にはg:freebasic_langに設定されることになる」という感じかと思います(雑訳ですが)

あと、日本語と英語記述の間の空白はちゃんと入れることを留意、かな

2022-09-22 09:55 UTC, tsuyoshicho commented on doc/filetype.jax
> +応する。方言が明示的に指定されていない場合は、"fb "が使用される。
ここも
「場合は、"fb" が使用される」
というような空白置きになります。
(クォート内に空白が増えてたのと、句読点直後は空白不要になるはずなので注意)

2022-09-22 09:55 UTC, tsuyoshicho commented on doc/filetype.jax
> +たとえば、方言をデフォルトの "fblite "に設定し、#langディレクティブのオーバーラ
ここは、
「方言のデフォルトを "fblite" に設定し」
という感じかな

あと、オーバーライドという用語があるわけじゃない気がするので、上書き、でいいかと

2022-09-22 09:55 UTC, tsuyoshicho commented on doc/filetype.jax
> +イドを許可するには、次のコマンドを使用する。>
`。>` とせずに `: >` のままで大丈夫です。

2022-09-22 15:57 UTC, ryicoh commented on doc/filetype.jax
> +れる。これらのグローバル変数は、概念的にはfbcオプションの-forcelangと-langに対
>あと、日本語と英語記述の間の空白はちゃんと入れることを留意、かな
承知です。

>最初に g:freebasic_forcelang で見つかる名前
これ全体にかかってるものと勘違いちゃっていました😂

こちら修正しました。

https://github.com/vim-jp/vimdoc-ja-working/pull/1138/commits/09a2f35ae4efe86089ae0e9ffb8d3da27996d913

2022-09-22 15:58 UTC, ryicoh commented on doc/filetype.jax
> +応する。方言が明示的に指定されていない場合は、"fb "が使用される。
こちら修正しました。！
https://github.com/vim-jp/vimdoc-ja-working/commit/09a2f35ae4efe86089ae0e9ffb8d3da27996d913

2022-09-22 16:00 UTC, ryicoh commented on doc/filetype.jax
> +たとえば、方言をデフォルトの "fblite "に設定し、#langディレクティブのオーバーラ
こちら修正しました。
https://github.com/vim-jp/vimdoc-ja-working/pull/1138/commits/16447dd64357b9526a6689db6891bf526f05677d

2022-09-23 05:15 UTC, tsuyoshicho requested changes
前の指摘は、概要的に言ってしまったこともあり、子細な部分がうまくつたわっていませんでした。
訳がこなれてきているので、その訳に手を入れた状態を提示して指摘をしています。

あと、全体指摘としてWikiにある [autofmtプラグイン](https://github.com/vim-jp/vimdoc-ja-working/wiki/Guide#autofmt-%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3) でフォーマットしておくのは留意してください。

2022-09-23 05:15 UTC, tsuyoshicho commented on doc/filetype.jax
> +の4つをそれぞれ別の言語として扱うことを目的である。
```suggestion
このプラグインは、FreeBASIC 方言である "fb", "qb", "fblite", "deprecated" の4
つをそれぞれ別の言語として扱うことを目的としている。
```

2022-09-23 05:15 UTC, tsuyoshicho commented on doc/filetype.jax
> +用される。
```suggestion
これらの方言は、最初に g:freebasic_forcelang で見つかる名前、次に編集しはじめ
たファイル内の #lang ディレクティブもしくは $lang メタコマンド、最終的には
g:freebasic_lang によって設定されることになる。これらのグローバル変数は、概念
的には fbc のオプション -forcelang と -lang に対応する。方言が明示的に指定され
ていない場合は、"fb" が使用される。
```

2022-09-23 05:15 UTC, tsuyoshicho commented on doc/filetype.jax
> +可するには、次のコマンドを使用する: >
```suggestion
たとえば、方言のデフォルトを "fblite" に設定ながら #lang ディレクティブでの上
書き許可するには、次のコマンドを使用する: >
```

2022-09-23 06:48 UTC, ryicoh commented
> あと、全体指摘としてWikiにある [autofmtプラグイン](https://github.com/vim-jp/vimdoc-ja-working/wiki/Guide#autofmt-%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3) でフォーマットしておくのは留意してください。

ci 欲しいですね〜

2022-09-23 06:49 UTC, ryicoh commented on doc/filetype.jax
> +の4つをそれぞれ別の言語として扱うことを目的である。
ありがとうございます！取り込みます！

2022-09-23 10:09 UTC, tsuyoshicho approved these changes

2022-09-26 01:57 UTC, h-east reviewed
ひと通りレビューしました。

2022-09-26 01:57 UTC, h-east commented on doc/filetype.jax
> +ていない場合は、"fb" が使用される。
ここの翻訳結構難しいですね。
- 冒頭は`The dialect`なので「これらの」は不要だと思います。
- 「g:freebasic_forcelang、#lang、$lang の順に値をチェックして最初に見つかった方言名を採用。見つからなかったら g:freebasic_lang の値を採用」という流れだと思うので、そのような訳に修正しました。
- `These global variables conceptually map to ～` の文は「g:freebasic_forcelang は fbc の -forcelang に対応していて、g:freebasic_lang は fbc の -lang に対応している」ということを言っているのだと思うので、文末を「対応している」としました。

```suggestion
方言は、g:freebasic_forcelang、編集中のファイルの #lang ディレクティブ、または
$lang メタコマンドで見つかった最初の名前、または最終的に g:freebasic_lang に設
定される。これらのグローバル変数は、概念的には fbc オプションの -forcelang お
よび -lang に対応している。方言が明示的に指定されていない場合は、"fb" が使用さ
れる。
```

2022-09-26 01:57 UTC, h-east commented on doc/filetype.jax
> +フリーベーシック(FREEBASIC)				*ft-freebasic-plugin*
既存の訳に倣ってカタカナ表記を追加されたのだと思います。
ここは、既存の訳が良くない(言語名をわざわざカタカナ表記併記する必要はないのと、highlightがされなくなる)ので原文ままで良いです。

既存部分の修正についてはIssueを立てましたので、そちらでやります。
#1142

```suggestion
FREEBASIC						*ft-freebasic-plugin*
```

2022-09-26 01:57 UTC, h-east commented on doc/filetype.jax
> +書きを許可するには、次のコマンドを使用する: >
- 既存訳だと「例えば」の方が「たとえば」より圧倒的に多いので「例えば」でお願いします。
  (以前 ci (dict.yml というか nvcheck)に入れようという話があった気がする...)
  議論用のIssueを立てました #1143
- 「設定ながら」というのが個人的には違和感がありました。原文は `but` なので、「設定するが」か「設定しつつ」が妥当かなぁと思います。

```suggestion
例えば、方言のデフォルトを "fblite" に設定するが、#lang ディレクティブの上書き
を許可するには、次のコマンドを使用する: >
```

2022-09-26 02:11 UTC, h-east commented on en/filetype.txt
> +     let g:freebasic_lang = "fblite"
インデントが既存のものと異なっています(タブ1つにすべき)。
原文の修正が必要ですので、専用スレッドにレスしました。
https://github.com/vim-jp/issues/issues/1387#issuecomment-1257382236

2022-09-28 13:47 UTC, ryicoh commented
@h-east 
レビュー＆提案ありがとうございました。！取り込ませていただきました 🙏 

> インデントが既存のものと異なっています(タブ1つにすべき)。

こちらは、原文に合わせてそのままの方がいいでしょうか？

2022-09-28 23:52 UTC, h-east approved these changes

2022-09-28 23:52 UTC, h-east commented
@ryicoh 
> こちらは、原文に合わせてそのままの方がいいでしょうか？

はい。原文が修正されるまでは、そのままでOKです。

2022-09-29 09:38 UTC, tsuyoshicho approved these changes
細かい言葉遣いまわりで気になる箇所がなくはないんですが、それは全体的にいろいろあると思うので、今回これでいいと思います。

2022-09-29 09:38 UTC, merged