Update various.{txt,jax}
vim-jp/vimdoc-ja-working pull request #1189
Opened 2022-10-30 06:40 UTC by tsuyoshicho

翻訳しました、よろしくおねがいします。

2022-11-12 08:31 UTC, tsuyoshicho commented
Vim 9.0.0861 に追従

2022-11-14 05:04 UTC, k-takata approved these changes

2022-11-14 05:04 UTC, k-takata requested changes
間違えました。

2022-11-14 09:29 UTC, tsuyoshicho commented on doc/various.jax
> +			る。
ちゃんと翻訳しきれてない感じですね...ありがとうございます。

2022-11-14 12:03 UTC, k-takata approved these changes

2022-11-14 12:03 UTC, merged

2022-11-14 12:03 UTC, k-takata commented
thx