Update vim9.{txt,jax}
vim-jp/vimdoc-ja-working pull request #1228
Opened 2023-03-06 12:12 UTC by h-east

2023-03-09 00:06 UTC, h-east commented on doc/vim9.jax
> +  ん。例えば、`:throw` を `:th` と書くことはできません。 *vim9-No-shorten*
新ノートPCで作業すると Unexpected な変更があるなぁ。気を付けねば。

```suggestion
  ん。例えば、`:throw` を `:th` と書くことはできません。 *vim9-no-shorten*
```

2023-03-11 09:06 UTC, tsuyoshicho requested changes
宣言 の前まで見ました。

2023-03-12 03:24 UTC, tsuyoshicho reviewed
最後まで見ました。
前を含め、コメント的なのがそれなりにあって微妙かもですが...

2023-03-12 03:24 UTC, tsuyoshicho commented on doc/vim9.jax
> +使います:
ここは

```suggestion
任意の型を持つ値について、それをブーリアンとして使いたい場合は、`!!` 演算子を
使います:
```

ではないかと

2023-03-12 03:24 UTC, tsuyoshicho commented on doc/vim9.jax
> +JavaScript のような言語から、このような便利な構文があります: >
```suggestion
JavaScript のような言語には、このような便利な構文があります: >
```

実際にこの動作が導入されてないことの説明文なので、導入のFromじゃなくて、引用的な意味かと思います。

2023-03-12 03:24 UTC, tsuyoshicho commented on doc/vim9.jax
> +を検討しました:
英語だと明確ですが、importじゃなく(sourceによる)読み込みだと上手く言える方法があるといいんですが...

importの説明での読み込みだから通じるかな?

2023-03-16 14:23 UTC, h-east commented on doc/vim9.jax
> +コンパイル時に与えることができ、実行時のエラー処理は必要ありません。
追加しました。

2023-03-16 14:25 UTC, h-east commented
まだ反映漏れがいくつかあります。

2023-03-16 22:46 UTC, tsuyoshicho commented on doc/vim9.jax
> -function with |<SID>| you should use|<ScriptCmd>|. For example: >
あ、For exampleの前ももう1つスペースが必要かも。
(Insteadの前は入れた)

2023-03-16 22:59 UTC, tsuyoshicho commented on doc/vim9.jax
> +コマンドや `||` 演算子など、条件が使われる場所では、ブーリアンライクな値しか受
ブーリアンライクは、ちょっと説明不足(わかるとはいえ)な気がしました。

というか真偽値とブーリアンと混在してますね。
(Booleanのところの説明だと括弧書きしてるから、全体としてどうするのがいいか難しい)

2023-03-18 09:49 UTC, h-east commented on doc/vim9.jax
> +			ンパイルする場合、"ClassName" とすることもできます。
fixed.

2023-03-18 10:05 UTC, h-east commented on doc/vim9.jax
> +Calling a function in an expr option ~
translated

2023-03-18 10:07 UTC, h-east commented on doc/vim9.jax
> +この背後にある理由は、型が宣言され、リストが渡されて変更された場合、宣言は常に
fixed

2023-03-18 10:18 UTC, h-east commented on doc/vim9.jax
> +す。 {not implemented yet: class, interface}
https://github.com/vim-jp/issues/issues/1387#issuecomment-1474805278

2023-03-18 10:21 UTC, h-east commented on doc/vim9.jax
> +これにより、"myscript.vim" に export された各項目は、"myscript.item " として利
「等」を付けました。

2023-03-18 10:24 UTC, h-east commented on doc/vim9.jax
> -function with |<SID>| you should use|<ScriptCmd>|. For example: >
> あ、For exampleの前ももう1つスペースが必要かも。

編集して入れました。

2023-03-18 10:26 UTC, h-east commented on doc/vim9.jax
> +ことができるようになります。
修正しました。あと「便利」を入れました。

2023-03-18 10:36 UTC, h-east commented on doc/vim9.jax
> +使用されます。これは異なるので、別のコマンドを使うのがよいでしょう。`var` で
ここはこのままにします。

2023-03-18 10:38 UTC, h-east commented on doc/vim9.jax
> +を検討しました:
通じると思うのでこのままで。

2023-03-18 10:56 UTC, h-east commented on doc/vim9.jax
> +コマンドや `||` 演算子など、条件が使われる場所では、ブーリアンライクな値しか受
s/ブーリアンライク/ブーリアンのような/
にしました。
からの～
このファイル内は「真偽値」に統一しました。

2023-03-18 11:00 UTC, h-east commented
`item`も「項目」と「アイテム」が混在していたので「項目」に統一しました。

これでレビュー指摘対応したと思います。

2023-03-18 12:07 UTC, tsuyoshicho reviewed
2つコメントしました。

2023-03-18 12:18 UTC, tsuyoshicho approved these changes
LGTM

2023-04-01 00:45 UTC, merged

2023-04-01 00:45 UTC, h-east commented
Thanks for review.