Translate map
vim-jp/vimdoc-ja-working pull request #1281
Opened 2023-06-21 08:49 UTC by k-takata

2023-06-24 00:02 UTC, tsuyoshicho requested changes
見てみました。

2023-06-24 00:02 UTC, tsuyoshicho commented on doc/map.jax
> +定期議されている場合、{repl} は Vim9 script 内で実行されます。つまりこれは、コ
```suggestion
定義されている場合、{repl} は Vim9 script 内で実行されます。つまりこれは、コ
```

typoですかね?

2023-06-26 05:30 UTC, k-takata commented
指摘反映しました。

2023-06-26 12:35 UTC, tsuyoshicho approved these changes

2023-06-29 00:19 UTC, h-east reviewed
ひと通り確認しました。指摘項目以外はLGTM:+1:です。

2023-06-29 00:19 UTC, h-east commented on doc/map.jax
> +   1.13 KITTY キーボードプロトコルを使ったマップ |kitty-keyboard-protocol|
ここと L1038 が KITTY になっています。(原文は `Kitty`)

2023-06-29 02:12 UTC, k-takata commented on doc/map.jax
> +   1.13 KITTY キーボードプロトコルを使ったマップ |kitty-keyboard-protocol|
fixed

2023-06-29 03:36 UTC, h-east approved these changes

2023-06-29 03:36 UTC, merged

2023-06-29 03:37 UTC, h-east commented
Thanks:+1: