Update builtin.{txt,jax} only related getbufoneline(), getcellwidths()
vim-jp/vimdoc-ja-working pull request #1286
Opened 2023-07-20 23:49 UTC by h-east

訳を統一するため、`{setcellwidths()`の訳を一部変更しています。

2023-07-21 12:37 UTC, tsuyoshicho requested changes
確認しました

2023-07-21 12:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		|setcellwidths()| によって上書きされる文字範囲のセル幅の
```suggestion
		|setcellwidths()| によって上書きされた文字範囲のセル幅の
```

overridden なので過去形でいいはず

2023-07-21 12:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		を参照。
```suggestion
		らなるリストを返す。その行のみの取得については `getbufoneline()`
		を参照。
```

これそのままだとダメとは思いますが、意図を伝えるために書いています
このonlyはthe line(その行)だけであることに掛っていると思います

2023-07-21 22:18 UTC, h-east commented on doc/builtin.jax
> +		を参照。
「1 行のみの取得」としました。

2023-07-21 23:05 UTC, tsuyoshicho approved these changes

2023-07-26 11:41 UTC, merged

2023-07-26 11:41 UTC, h-east commented
Thanks for review.