Update builtin.{txt,jax} (partly#2)
vim-jp/vimdoc-ja-working pull request #1328
Opened 2023-10-12 15:54 UTC by h-east

変更内容:
- 一覧の変更/追加はすべて反映させました。
- 一覧に変更/追加のあった関数の本体の変更/追加もすべて反映しています。(同ファイル内に本体が存在する場合)
- 後は、本体の`col()`の手前までの関数の修正もおこなっています。

2023-10-14 02:57 UTC, tsuyoshicho requested changes
確認しました。

2023-10-14 02:57 UTC, tsuyoshicho commented on doc/builtin.jax
> +
note
ここに空行はないみたいです

2023-10-14 02:57 UTC, tsuyoshicho commented on doc/builtin.jax
>  readblob({fname})					*readblob()*
```suggestion
readblob({fname} [, {offset} [, {size}]])			*readblob()*
```

2023-10-14 02:57 UTC, tsuyoshicho commented on doc/builtin.jax
> +		レクトリに使用される。カレントディレクトリ内のスワップファイル
'directory' オプションは、検査するディレクトリとして使用される。

だとどうでしょうか?

2023-10-14 02:57 UTC, tsuyoshicho commented on doc/builtin.jax
> +			" テキスト "	  there" で、'h' のところに 't:
comment
原文からしてですが、't は 「t でマークされている」
とかほしいですね

2023-10-14 03:45 UTC, k-takata commented on doc/builtin.jax
> +		詳細については。|win_findbuf()| を参照。
"for finding more" は、現在のタブページだけではなくさらにウィンドウを探すためにはということを言っていると思います。

2023-10-15 03:35 UTC, h-east commented on doc/builtin.jax
> +		詳細については。|win_findbuf()| を参照。
改行位置は単なるミスです :sweat:
@k-takata さんの提案を採用しました。

2023-10-15 03:52 UTC, h-east commented on doc/builtin.jax
> +			" テキスト "	  there" で、'h' のところに 't:
今回はこのままで。(typo報告スレからlink張りました)

2023-10-15 04:45 UTC, tsuyoshicho requested changes
一箇所以外はLGTM

2023-10-15 04:45 UTC, tsuyoshicho commented on doc/builtin.jax
> +		クスを持ち、|v:val| はバイトの値を持つ。
```suggestion
		|v:val| はその項目の値を持つ。{object} が |Blob| であれば、
		{expr} の内部では |v:key| は現在のバイトのインデックスを持ち、
		|v:val| はバイトの値を持つ。
```
まず、{object}のところは修正内容例でしかなく、改行とかが変だったのを断わってなかったです。
すみません

それ込みで再確認で気付いたこととして
* 記述の重複(リストのもの)があるので削除する対応
* 記述をList/Blobで合せる
* 整形
が必要とおもわれます。

今回の修正提案はすべて対応したものを出していますので、今一度確認ください。

2023-10-15 06:09 UTC, h-east commented on doc/builtin.jax
> +		クスを持ち、|v:val| はバイトの値を持つ。
リストは前の文が「の場合:」のため、「の場合、」だと連続してしまうので「であれば、」にしています。
Blobはそれがないので「の場合、」としています。

2023-10-15 06:16 UTC, tsuyoshicho commented on doc/builtin.jax
> +		クスを持ち、|v:val| はバイトの値を持つ。
了解です。
最初はどちらも場合のほうがいいかなと思いましたが、連続はたしかに気になる(というか読みにくい)ので断念したところはありますので、納得です。

2023-10-15 06:27 UTC, tsuyoshicho approved these changes

2023-10-15 07:08 UTC, k-takata commented on doc/builtin.jax
> +		これは、{size} が明示的に設定されている場合に、Unix 上の文字デ
character deviceはそのままキャラクターデバイスでいいと思います。

2023-10-21 09:26 UTC, merged