Update options.{txt,jax}
vim-jp/vimdoc-ja-working pull request #1339
Opened 2023-10-17 17:47 UTC by h-east

現時点の最新に追従しました。

2023-11-03 10:59 UTC, tsuyoshicho requested changes
確認しました。

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	次に、このオプションが検査され、マッチするものがあり、プロトコルが指定
suggestion
最初にtermcapエントリが設定されたら、おそらく組み込みリストが使用される。

ではないかと思います。

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +			    CSI ?4m	modifyOtherKeys 状態を要求する
```suggestion
			    CSI >4;2m	modifyOtherKeys を有効にする
			    CSI ?4m	modifyOtherKeys の状態を要求する
```

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	ある。
おそらくtypoと思います
lispwordsの記述と合せました。

```suggestion
	|'lisp'| オプションとともに有効化された場合、Lisp のインデントに影響を与える項目のコン
	マ区切りのリスト。現在サポートされている項目は 1 つだけで
	ある。
```

(要改行調整)

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +			ペースを先頭に置く場合に使用する。
comment
これはあくまで、こうかなという程度なのですが

```suggestion
			|lcs-multispace| 値と似ているが、先頭のスペースのみを
			対象とする。先頭複数ス
			ペースで |lcs-lead| もオーバーライドする。
```

のような感じがします

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	コールバック関数の深さを最大にするためにも使用される。
maximize (最大化) ではないので

```suggestion
	コールバック関数の最大の深さをにも使用される。
```

ではないかなと思いました。

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	プションは、ファイルの2個のバージョン間の違いを見るのに便利である。
```suggestion
	プションは、ファイルの 2 個のバージョン間の違いを見るのに便利である。
```
にします?

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	S S   'showcmd' の内容については、'showcmdloc' を参照。
ここは、各項目の説明なので

```suggestion
	S S   'showcmd' の内容、'showcmdloc' を参照。
```

と Sが showcmdの内容であること、付加情報としての参照というかたちになるかなと

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	      あると中央部分があり、その左右に空白がある。
```
No width fields allowed.
```
が削除されてしまっているかと

以前のは以下です
```
欄 width は指定できない。
```

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	   更しても書式が崩れることはない (念のため 8 のままにしておきく)。ファ
```suggestion
	   更しても書式が崩れることはない (念のため 8 のままにしておく)。ファ
```

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +'ttyfast' 'tf'		切替	(既定ではオフ)
(default on)
とありますので

```suggestion
'ttyfast' 'tf'		切替	(既定ではオン)
```

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
> +	以前は一部の端末名にのみデフォルトが設定されていたが、最近ではほぼすべ
```suggestion
	以前は一部の端末名にのみデフォルトで設定されていたが、最近ではほぼすべ
```

かな?

2023-11-03 10:59 UTC, tsuyoshicho commented on doc/options.jax
>  				 VMSでの既定値: "sys$login:vimfiles/view")
以前のがのこってます

2023-11-03 12:56 UTC, k-takata commented on doc/options.jax
> +	`CTRL-L`の後に表示される文字が消えてしまう等の問題に気付いた場合は、こ
```suggestion
	`CTRL-L` の後に表示される文字が消えてしまう等の問題に気付いた場合は、こ
```

2023-11-03 14:31 UTC, h-east commented on doc/options.jax
> +	次に、このオプションが検査され、マッチするものがあり、プロトコルが指定
遠慮なくsuggestion元も提示ください。(特定するのに時間が掛かってしまうので)
で、東訳で合っていると思います。

2023-11-03 14:54 UTC, h-east commented on doc/options.jax
> +			ペースを先頭に置く場合に使用する。
違うんじゃないでしょうか？
1文にするのであれば、「先頭の複数スペースのために |lcs-lead| もオーバーライドする」かなぁ。

2023-11-03 15:06 UTC, h-east commented on doc/options.jax
> +	プションは、ファイルの2個のバージョン間の違いを見るのに便利である。
このオプションの当該箇所の前の変更があっただけなのでこのままにしています。ここを変更すると、このオプション内の文章の同様に変更が必要になって芋づる式になるので、今回はこのままで。

2023-11-03 16:00 UTC, h-east commented on doc/options.jax
> +	以前は一部の端末名にのみデフォルトが設定されていたが、最近ではほぼすべ
Google翻訳/DeepL翻訳とも「～にのみ」ですのでこのままとします。

2023-11-04 03:47 UTC, tsuyoshicho commented on doc/options.jax
> +	次に、このオプションが検査され、マッチするものがあり、プロトコルが指定
了解しました、どの道改行調整とかは必要になりますが、出すようにします

2023-11-04 03:48 UTC, tsuyoshicho commented on doc/options.jax
> +	プションは、ファイルの2個のバージョン間の違いを見るのに便利である。
わかりました。

2023-11-04 05:30 UTC, tsuyoshicho commented on doc/options.jax
> +			ペースを先頭に置く場合に使用する。
あー、なるほどそちらのほうがよさそうですね、了解です。

2023-11-04 05:31 UTC, tsuyoshicho approved these changes

2023-11-04 05:31 UTC, tsuyoshicho approved these changes

2023-11-10 21:33 UTC, merged