Update builtin.{txt,jax} (Partly#3)
vim-jp/vimdoc-ja-working pull request #1340
Opened 2023-10-24 16:05 UTC by h-east

a～n で始まる関数の変更を反映しました。

2023-10-31 02:26 UTC, tsuyoshicho reviewed
細かい確認は不十分ですが、まず確認した内容から

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
> +		号は行の長さより1大きい値を返す。
```suggestion
		号は行の長さより 1 大きい値を返す。
```
かえって読みにくい?

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
> +				にすることができる。
インデント空白の変更と改行の整形が必要と思われます

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
> +		それ以外のときはエラーとなり、ゼロを返す。
```suggestion
		それ以外のときはエラーとなり、0 を返す。
```
数字表記でいいはず

と思いますが、なんか0とzero表記がいろいろあって、どう書くのがいいのかは確定じゃないかも

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
> +		{callback} または {buf} が無効な場合はゼロを返す。
```suggestion
		{callback} または {buf} が無効な場合は 0 を返す。
```
同上

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
> +		からマッピングを復元する。dict.buffer が true の場合、バッファ
TRUE以外で true があったら、「真の場合」として意味を記載していると思われます

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
>  		ならない。
ここで、上の行の記述が表記(翻訳)揺れになってますね

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
> +
この空行はないようなので、一応指摘

2023-10-31 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
> +		    limit	返される {list} 内のマッチの最大数。ゼロは制限
ゼロの件、ここも

2023-10-31 16:23 UTC, h-east commented on doc/builtin.jax
> +				にすることができる。
本家の方も修正しました。(typo報告スレにpatch貼り付け)

2023-10-31 16:28 UTC, h-east commented on doc/builtin.jax
> +		それ以外のときはエラーとなり、ゼロを返す。
原文が`Zero`の場合は`ゼロ`、`0`の場合はそのまま`0`としています。
既存でも ゼロ/0 表記分かれているので今回はこのままで。

2023-10-31 16:37 UTC, h-east commented on doc/builtin.jax
>  		ならない。
具体的に指摘お願いします。

2023-11-01 05:27 UTC, k-takata commented on doc/builtin.jax
> +		なくとも 1000 の空いている ID を自動的に選択する。
```suggestion
		引数 {id} が指定されていないか -1 の場合、|matchadd()| は、
		空いている ID (1000 以上) を自動的に選択する。
```
こうした方が自然かなと思いました。

2023-11-01 11:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		それ以外のときはエラーとなり、ゼロを返す。
そうですね、なにか新しい指針になるなにかが出るまでは、あわせるのは確実ですし。
了解です。

2023-11-01 11:40 UTC, tsuyoshicho commented on doc/builtin.jax
>  		ならない。
あ、すいません、不十分でした
今回の範囲ではないですが

```
{expr} must evaluate to a |Float| or a |Number|.
```

という文に対しての翻訳が

多くの箇所では `{expr} は |Float| または |Number| に評価されなければならない。` となっていますが、ここは `{expr} は浮動小数点数 (|Float|) か 数値 (|Number|) でなければならない。` というものでした。

範囲外ではあるので、Noteという程度ですが

2023-11-01 13:40 UTC, h-east commented on doc/builtin.jax
> +		なくとも 1000 の空いている ID を自動的に選択する。
> （あるいは、「1000 以上の空いている ID」か。）

こちらを採用しました。

2023-11-01 13:53 UTC, h-east commented on doc/builtin.jax
>  		ならない。
ここだけではなく他4か所も同じ訳(`{expr} は浮動小数点数 (|Float|) か 数値 (|Number|) でなければならない。`)になっていて意味は通じるのでこのままとします。
気になるようでしたら、別途スレ立てお願いします。

2023-11-03 02:26 UTC, tsuyoshicho commented on doc/builtin.jax
>  		ならない。
そうですね、どこかで整理したのを出すということで

2023-11-03 09:37 UTC, tsuyoshicho requested changes
全部確認しました。
ここでの指摘点の対応が完了したらapproveします

2023-11-03 09:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		字列を返す expand('%:h') とは異なる。
suggestion:
まず、specifiyじゃないので、指定ではないかなと(一応ですが)

その上でまとめると
「バッファ名を指定せずに空の文字列を返す expand('%:h') とは異なる。」
よりは
「バッファ名が(引数に)なく空の文字列を返す expand('%:h') とは異なる。」
かなと思いました。

カッコのところはニュアンス的で、このままだと使えませんが...

全部を統合するとこの訳でいったほうがよさそう、というのであればOKです

2023-11-03 09:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		いるように、大文字と小文字は区別される。
既存の訳の残りと混在して、文が変になってます

(「'ignorecase' はここでは適用されず、常に大文字・」 は削除かな)

2023-11-03 09:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		  "abbr"     これが短縮入力 |abbreviations| の場合は True。
comment
この True は真かなと思いましたが、どうだろう...

2023-11-03 09:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		  "mode_bits" Vim の内部バイナリ表現の "mode"。|maplist()| は
comment
日本語的に

```suggestion
		  "mode_bits" "mode" の Vim の内部バイナリ表現。|maplist()| は
```

だと座りがいいかなと思いました。

2023-11-03 09:37 UTC, tsuyoshicho commented on doc/builtin.jax
> +		   ct	    端末ジョブモード経由のコマンドライン編集
suggestion
経由よりは
```suggestion
		   ct	    端末ジョブモードでのコマンドライン編集
```
とするのはどうでしょう?

2023-11-10 23:22 UTC, tsuyoshicho approved these changes
LGTM!

2023-11-11 20:54 UTC, merged