Add vim9class.{txt,jax}
vim-jp/vimdoc-ja-working pull request #1360
Opened 2023-11-10 21:08 UTC by h-east

マージする場合は
https://github.com/vim-jp/vimdoc-ja/pull/278
もマージお願いします。

2023-11-10 23:48 UTC, tsuyoshicho requested changes
とりあえずtypoの指摘を先に

2023-11-10 23:48 UTC, tsuyoshicho commented on doc/vim9class.jax
> +ソッドの名前を変更する必要がある。大したことではiないが、それでもデメリットは
```suggestion
ソッドの名前を変更する必要がある。大したことではないが、それでもデメリットは
```

2023-11-10 23:48 UTC, tsuyoshicho commented on doc/vim9class.jax
> +{not implemented yet}
comment
{まだ実装されていない}、といった日本語はしないということでしょうか?

2023-11-11 20:52 UTC, h-east commented on doc/vim9class.jax
> +{not implemented yet}
普通に訳すとハイライトされないのでそのままにしていました。カッコ内の後ろに訳を入れてみました。

2023-11-11 23:24 UTC, tsuyoshicho commented on doc/vim9class.jax
> +{not implemented yet}
なるほど、了解です

2023-11-17 14:23 UTC, h-east commented
@tsuyoshicho 問題無ければ requested changes をオフにしてもらえますか？
もしくは、どこを直せていないか教えてください。

2023-11-17 22:43 UTC, merged

2023-11-18 00:14 UTC, tsuyoshicho commented
応答遅れてすみません、たしかにそうでした