Update builtin.{txt,jax}
vim-jp/vimdoc-ja-working pull request #1423
Opened 2024-01-30 13:16 UTC by h-east

2024-01-30 14:10 UTC, tsuyoshicho requested changes
まず気付いたところです

2024-01-30 14:10 UTC, tsuyoshicho commented on doc/builtin.jax
> +		{expr1} は |List|, |String|, |Blob| または |Dyowictionary| で
```suggestion
		{expr1} は |List|, |String|, |Blob| または |Dictionary| で
```

2024-01-30 14:10 UTC, tsuyoshicho commented on doc/builtin.jax
> +		{expr2}が |string| の場合、{expr2} 内では |v:val| は現在の項目
```suggestion
		{expr2} が |string| の場合、{expr2} 内では |v:val| は現在の項目
```

2024-01-30 14:18 UTC, h-east commented on doc/builtin.jax
> +		{expr1} は |List|, |String|, |Blob| または |Dyowictionary| で
うわぁ 💦 。最近視力が落ちた(老眼)のでこれ系増えてきた。気を付けます。

2024-01-30 14:23 UTC, tsuyoshicho commented on doc/builtin.jax
> +		{expr1} は |List|, |String|, |Blob| または |Dyowictionary| で
気にならさらず...自分はよくやってた気がするしw

2024-02-01 12:53 UTC, tsuyoshicho approved these changes

2024-02-05 11:49 UTC, merged