Update builtin.{txt,jax}.  Up to function name m*().
vim-jp/vimdoc-ja-working pull request #1583
Opened 2024-06-17 17:52 UTC by h-east

2024-06-17 17:53 UTC, h-east commented
ひとまず、関数名 `m～()` まで完了。

2024-06-19 11:31 UTC, tsuyoshicho commented
見ていきますが、ちょっと時間と期間がかかると思います
(一回見落しやってるので、慎重にいく)

2024-06-22 02:02 UTC, tsuyoshicho requested changes
気付けた範囲ですが、以下だけだと思います。

2024-06-27 16:56 UTC, h-east commented on doc/builtin.jax
> +		戻り値の型: list<any>
(原文は `<` ですよね？) typoなので削除しています。
https://github.com/vim-jp/issues/issues/1433#issuecomment-2176633202

2024-06-27 23:35 UTC, tsuyoshicho commented on doc/builtin.jax
> +		戻り値の型: list<any>
あ、オオボケしましたorz
それにここで閉じる内容じゃないですもんね...

2024-06-27 23:35 UTC, tsuyoshicho approved these changes

2024-06-30 23:42 UTC, merged

2024-06-30 23:42 UTC, h-east commented
Thanks for the review!