Update channel from Vim 8.0 to 8.1
vim-jp/vimdoc-ja-working pull request #300
Opened 2018-08-08 06:14 UTC by h-east

#207

2018-08-08 13:52 UTC, h-east commented
レビュー指摘箇所を修正しました。

2018-08-09 05:10 UTC, mnishz requested changes

2018-08-09 05:10 UTC, mnishz commented on doc/channel.jax
> +プロンプト行でEnterキーを押すと、|prompt_setcallback()| が呼び出されます。通常
以下の部分ですが、"the callback set with" が抜けているように思いました。
> When pressing Enter in the prompt line the callback set with When pressing Enter in the prompt line the callback set with |prompt_setcallback()| is invoked.

> |prompt_setcallback()| で設定されたコールバックが呼び出されます。

でしょうか。

2018-08-09 05:10 UTC, mnishz commented on doc/channel.jax
> +り、プロンプトの下の (次のプロンプトの上) バッファに表示します。
言葉の問題かもしれませんが、
> プロンプトの下の (次のプロンプトの上) バッファに表示

よりも
> バッファ内のプロンプトの下 (次のプロンプトの上) に表示

のほうがよいかな？と思いました。

2018-08-09 05:14 UTC, mnishz commented
"Request changes" だと "×" が付くんですね。"Comment" にしておけばよかった。。

2018-08-09 05:34 UTC, h-east commented
@mnishz 指摘反映しました。Thanks:+1:

2018-08-09 08:08 UTC, mnishz commented on doc/channel.jax
> +クが呼び出されます。通常は、その行をジョブに送信します。 別のコールバックは、
修正どうもありがとうございました。
> 通常は、その行をジョブに送信します。

の後に半角スペースが入っているようです。他に修正があれば一緒に直していただけばと思います。

2018-08-09 08:09 UTC, mnishz approved these changes

2018-08-10 13:57 UTC, k-takata approved these changes

2018-08-10 14:13 UTC, merged

2018-08-10 14:31 UTC, h-east commented
レビューありがとうございました:+1: マージしました。

そういえば最後から10行目に書いてある

> (use Shift-CTRL-W to delete a word)

これ出来ないですね。(Vim 8.1.0264 on fedora, gVim 8.1.0191 on Win10)
そもそも、`Shift-CTRL-`の検出出来てたっけ？ドキュメントを直せばいいのかな？

2026-08-30 03:06 UTC, edwinmendoza202607-creator approved these changes

2026-08-30 03:08 UTC, edwinmendoza202607-creator commented on doc/channel.jax
> +*channel.txt*      For Vim バージョン 8.1.  Last change: 2018 Apr 18
alexisbeenedy07@gmail.com