Update {various,version8,vi_diff}.{txt,jax}
vim-jp/vimdoc-ja-working pull request #867
Opened 2021-01-04 15:46 UTC by h-east

2021-01-06 06:36 UTC, tsuyoshicho requested changes
various,vi_diff reviewd

2021-01-06 06:36 UTC, tsuyoshicho commented on doc/various.jax
>  			{count} が指定された場合は 'window' オプションがその値
ここの `{count}` は `[count]` になってます。
```suggestion
			[count] が指定された場合は 'window' オプションがその値
```

2021-01-06 06:36 UTC, tsuyoshicho commented on doc/various.jax
> +			{count} を省略し、ウィンドウが一つだけなら 'scroll' オ
```suggestion
			行の範囲をどれだけ表示するかは [count] に指定します。
			[count] を省略し、ウィンドウが一つだけなら 'scroll' オ
```

2021-01-06 06:36 UTC, tsuyoshicho commented on doc/various.jax
>  :{range}z[+-^.=]{count}	{range}に指定した行の周辺を表示します。{range} を省略
```suggestion
:[range]z[+-^.=][count]	[range]に指定した行の周辺を表示します。[range] を省略
```

2021-01-06 13:57 UTC, h-east commented on doc/various.jax
>  			{count} が指定された場合は 'window' オプションがその値
うっかりしてました。Thanks!

2021-01-06 23:17 UTC, tsuyoshicho approved these changes

2021-01-07 03:24 UTC, k-takata approved these changes

2021-01-07 08:11 UTC, merged

2021-01-07 08:11 UTC, h-east commented
Thanks for reviewing.