[WIP] update vim9.{txt, jax}
vim-jp/vimdoc-ja-working pull request #891
Opened 2021-03-01 10:29 UTC by kazukazuinaina

途中ですが、一旦PR出しておきます。
翻訳作業が一通り完了したらdraftを解除しようと考えています。

2021-03-09 13:52 UTC, tsuyoshicho requested changes
できる限りで指摘しました。

2021-03-09 13:52 UTC, tsuyoshicho commented on doc/vim9.jax
> +以下のとおりです:
```suggestion
は以下のとおりです:
```
と繋ぐほうがいいかも?

2021-03-09 13:52 UTC, tsuyoshicho commented on doc/vim9.jax
> +		る時に便利です。
```suggestion
		Vim9 script の文法と方式を使用して {cmd} を実行します。コマン
		ドを入力するときと、レガシースクリプトや関数を使用する時に便利
		です。
```

以前 repeat.txt での翻訳時に (Vim9 の) syntax and semantics を訳しており、一応合せる変更を指摘しておきます。
ただ、これが最適かは議論の余地があります。

https://github.com/vim-jp/vimdoc-ja-working/pull/873#discussion_r576741594

2021-03-13 15:25 UTC, kazukazuinaina commented
一旦、差分は翻訳完了したのでdraftを解除します。
おまたせして申し訳ないです。

2021-03-13 15:25 UTC, kazukazuinaina commented
未翻訳部分は別PRでやります。

2021-03-15 13:55 UTC, tsuyoshicho approved these changes
LGTM

2021-03-15 16:26 UTC, obcat commented on doc/vim9.jax
> +		ドを入力するときと、レガシースクリプトや関数を使用する時に便利
横からすみません 🐱
すでに翻訳済の部分で、`legacy` は `旧来の` と訳されているようなので、そちらに合わせたほうがよいかなと思いました。

2021-03-18 10:05 UTC, kazukazuinaina commented on doc/vim9.jax
> +		ドを入力するときと、レガシースクリプトや関数を使用する時に便利
了解です、修正します。
ご指摘ありがとうございます！

2021-03-18 10:07 UTC, kazukazuinaina commented
修正しました

2021-03-18 10:23 UTC, tsuyoshicho commented
ping @h-east @k-takata
次に進めるにも、先にこちらを見ていただいたほうがよいかと思いますので、連絡。

2021-03-21 12:33 UTC, h-east reviewed
https://github.com/vim/vim/commit/9faec4e3d439968e21ad74e917aebb289df8f849#diff-276d2fe6d42680e6055997d47473f23e9e2811387be6377ccc488071bb9d324f の変更が原文/訳文どちらにも反映されていないようです。
日付的には作業開始前のものなので、反映されていないのはおかしい気がします。
見直しをお願いします。

2021-03-21 12:33 UTC, h-east commented on doc/vim9.jax
> +場合はエラーが発生します。数字は、[]をつけてもつけなくても与えられます: >
空白追加。

```suggestion
場合はエラーが発生します。数字は、[] をつけてもつけなくても与えられます: >
```

2021-03-26 04:21 UTC, kazukazuinaina commented
@h-east 
> 一度最新に追従した方がいいかもしれませんね。

返信が遅れて大変申し訳無いです。
自分もこの意見に賛成で、一旦`vim9.txt`の最新に追従して更新し直しますね

2021-03-27 13:54 UTC, h-east commented on doc/vim9.jax
> +		す。
指摘通りに反映されていないです。

2021-03-27 13:56 UTC, h-east commented on doc/vim9.jax
> +- `:xit`、`:t`、`:k`、`:append`、`:change`、`:insert` と波括弧変数は使用できません。
こちらも反映されていません。

2021-03-27 14:11 UTC, h-east commented
> 一旦vim9.txtの最新に追従して更新し直しますね

作業された日(3/26)よりも明らかに前の変更が未だ反映されていないです。
https://github.com/vim-jp/vimdoc-ja-working/pull/891#discussion_r598267752 で言及した 8.2.2605 等。

2021-03-28 05:41 UTC, kazukazuinaina commented on doc/vim9.jax
> +- `:xit`、`:t`、`:k`、`:append`、`:change`、`:insert` と波括弧変数は使用できません。
すいませんでした。
反映してもう一度pushします。

2021-03-28 05:42 UTC, kazukazuinaina commented on doc/vim9.jax
> +		す。
この機能について知らなかったです。
次から使っていくようにしますね。

2021-03-28 05:53 UTC, kazukazuinaina commented
お手数おかけして申し訳ないです。
修正しました。

2021-04-05 16:20 UTC, kazukazuinaina commented
何度もレビューしていただき、ありがとうございました。
抜け、漏れが多くて申し訳ありませんでした。
指摘箇所を修正しました 🙇

2021-04-06 13:20 UTC, h-east commented on en/vim9.txt
> +Vim9 script: https://github.com/lacygoill/wiki/blob/master/vim/vim9.md
英文をそのまま vim9.jax にコピーしていますね。訳さないのですか？

同じ英文が vim9.txt の850～851行目にもあるので混同しないようにしてください。

2021-04-06 13:21 UTC, h-east commented on en/vim9.txt
> +Vim9 script: https://github.com/lacygoill/wiki/blob/master/vim/vim9.md
私が言っていること理解されていますか？
未翻訳部分については vim9.txt と vim9.jax でdiffを確認すればすべて反映済みかどうか確認できるので実施お願いします。
(5ブロック反映漏れがあります)

2021-04-19 10:58 UTC, kazukazuinaina commented
反映漏れ、翻訳忘れが多くて申し訳ありませんでした。
今後こういったミスをなくすように尽力したいと思います。

2021-04-21 17:56 UTC, h-east reviewed
PR中に原文が更新されていますが、このPRでは更新を取り込まずにこのまま進めて一旦マージしてしまいましょう。

2021-04-21 17:56 UTC, h-east commented on doc/vim9.jax
> +かれました。https://github.com/lacygoill/wiki/blob/master/vim/vim9.md
- `early adopter`はそのまま`アーリーアダプター`でいいかなと思いました。
- URLの前は「。」ではなく原文と同じ `: ` でお願いします。

```suggestion
また、このwikiも参考になるでしょう。これはVim9 scriptのアーリーアダプターによっ
て書かれました: https://github.com/lacygoill/wiki/blob/master/vim/vim9.md
```

2021-04-21 17:58 UTC, h-east approved these changes

2021-04-21 18:00 UTC, kazukazuinaina commented
@h-east

レビューありがとうございました！
また、コミットが遅れてすいませんでした…
次からミスを減らすようにします。

2021-04-22 04:33 UTC, merged

2021-04-22 04:33 UTC, k-takata commented
thx