Update {autocmd,change,cmdline,editing}.{txt,jax}
vim-jp/vimdoc-ja-working pull request #903
Opened 2021-04-23 03:50 UTC by obcat

翻訳しました。よろしくお願いします。

2021-04-23 08:53 UTC, h-east commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
(修正前からなのですが)英文にある行頭の`Note `が消えています。お手数ですが追加お願いします。
(あれ、Suggestが出来ない...)

2021-04-23 12:37 UTC, tsuyoshicho requested changes

2021-04-23 12:37 UTC, tsuyoshicho commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
```suggestion
			Note [fname] は自動コマンドを選択するのに使われる。コマンド
```

こうかな

2021-04-23 12:37 UTC, tsuyoshicho commented on doc/autocmd.jax
> +			使う?}
[fname]は利用するautocmdを選択するために利用され、適用されるバッファを選ぶためではない

的なニュアンスで記載を改訂できれば訳注は不要になるかもしれませんね(とはいえ、用法がよくわからないのは確か)

2021-04-23 13:35 UTC, obcat commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
了解です！

2021-04-23 13:46 UTC, obcat commented on doc/autocmd.jax
> +			使う?}
`[fname]`、私もよく分からなかったんですが、色々試していたら完全に理解できたっぽいので反映させておきます。（どうも説明しづらくて苦戦中ですが・・）

2021-04-23 13:59 UTC, h-east commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
` ```suggestion`～` ``` `を手打ちすればイケました。でも、Commentボックスの上部に`Insert a suggestion`アイコンが表示されてないんですよね。( @tsuyoshicho さんのPRでは表示されている)。なんでだろう。

2021-04-23 14:02 UTC, tsuyoshicho commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
もし、削除側にマウスをポイントしてからスタートしてしまうと出ないみたいです。
基本追加側で、行が選択されてる状態でやれば出るはずですが……、ただ指摘見ると追加側っぽいですよね、謎だ

2021-04-23 14:25 UTC, obcat commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
あ、もしかしたら、私がこのリポジトリ（を fork せず）に直 push してるからかもです・・
次回 PR 出すときは fork からやってみます。

2021-04-23 14:35 UTC, obcat commented
`Note: ` と、`[fname]` に対する詳細な訳注を追加しました。

2021-04-23 14:36 UTC, obcat commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
「説明が冗長」とか「にゃおーはふざけすぎ」などのご意見があればすぐ対応します。。

2021-04-23 14:39 UTC, tsuyoshicho commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
「数だ」は「数だけ」かな
モンティパイソンで SPAM! っていう手もあるけど、悪くはない気はするw

2021-04-23 14:48 UTC, obcat commented
タイポの修正と「にゃおー → SPAM!」を行いました。

2021-04-23 14:48 UTC, h-east commented on doc/autocmd.jax
> +			Note: [fname] は自動コマンドを選択するのに使われる。
`:`なしです。`Note`はハイライトされるので視認性は問題ないです。

```suggestion
			Note [fname] は自動コマンドを選択するのに使われる。
```

2021-04-23 14:51 UTC, obcat commented on doc/autocmd.jax
> +			Note: [fname] は自動コマンドを選択するのに使われる。
失礼しました。提案を取り込みました。

2021-04-23 14:54 UTC, h-east commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
うーん、そこまで訳注が膨らむのなら、本家の方をわかりやすく修正すべきな気がします。

2021-04-23 15:02 UTC, tsuyoshicho commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
まあ、たしかに……

2021-04-23 15:15 UTC, obcat commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
そうですね... 私も修正すべきだと思います。
本家に修正を提案するとして、ここ（`jax`）ではどのように記述しておくべきでしょうか…? 個人的には多少冗長になっても詳細な説明があったほうが良いと思います。

2021-04-24 12:16 UTC, h-east commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
本家に修正を提案することにフォーカスしていただければと思います。
現状は訳注を膨らませない方向で記述で良いと思います。
(無いと思いますが)提案がRejectされた時に訳注を膨らませるかどうかを考えれば良いのではないでしょうか？

2021-04-24 12:23 UTC, h-east commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
https://github.com/vim-jp/vimdoc-ja-working/pull/903#discussion_r619280855 で出来たので大丈夫だと思います。(たぶん)

2021-04-24 18:42 UTC, obcat commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
手打ち面倒だと思いますし直だと何か事故が起こるかもしれないのでやっぱり fork 経由でやることにします〜。ありがとうございます。

2021-04-24 18:43 UTC, obcat commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
そうですね、わかりました。その方向で調整します！

2021-04-24 19:05 UTC, obcat commented
`:doautoall` の訳注を元に戻しました。

2021-04-24 19:33 UTC, obcat commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
提案しました。https://github.com/vim/vim/issues/8147

2021-04-25 10:34 UTC, h-east commented on doc/autocmd.jax
> +			[fname] は自動コマンドを選択するのに使われる。コマンド
あ、手打ちではなくてちゃんと`Insert a suggestion`アイコンが表示されたんです。

2021-04-25 10:36 UTC, h-east approved these changes

2021-05-03 02:14 UTC, h-east commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
本家への提案取り込まれましたね。:+1:
https://github.com/vim/vim/commit/4c295027a426986566cd7a76c47a6d3a529727e7#diff-7fc4babd126f0b22993940da3ae8260a3b82ec20aa3dca54425bc4d27e6d8600

といことでこのPRマージします。

2021-05-03 02:15 UTC, merged

2021-05-03 05:57 UTC, obcat commented on doc/autocmd.jax
> +			"にゃおー" が表示される。}
お、うれしい！🙌
さすがに SPAM! は変えらちゃいましたねｗ

2021-05-03 05:57 UTC, obcat commented
Thanks!