Update vim9.{jax,txt}
vim-jp/vimdoc-ja-working pull request #905
Opened 2021-04-25 03:25 UTC by obcat

差分だけ翻訳しました。よろしくお願いします。

2021-04-30 02:06 UTC, tsuyoshicho requested changes
指摘できる部分だけですが、見ました。

2021-04-30 02:06 UTC, tsuyoshicho commented on doc/vim9.jax
> +使用してください。
```suggestion
`:lockvar` はローカル変数には機能しません。代わりに `:const` と `:final` を
使用します。
```

ここはandなので "か" ではなく "と" を使ってうまく説明しないといけない気がします。

2021-04-30 05:05 UTC, obcat commented on doc/vim9.jax
> +混乱を招く可能性がある場所ではエラーが発生するからです。#{{ や #{{ なら OK で
一緒だったw ありがとうございます。

2021-04-30 05:27 UTC, obcat commented on doc/vim9.jax
> +使用してください。
うーん、忠実に訳すとご提案の通りになるかとは思うんですが、第 1 文・第 2 文ともに現状のままのほうが実態に合っている気がします。理由はそれぞれ次のようなかんじです。
- `:lockvar` を `:def` 関数内のローカル変数に対して使用すると `E1178: Cannot lock or unlock a local variable` というエラーが発生するんですが、`機能しません` と書いてしまうと「エラーにはならないが効果はない」のようなニュアンスに取られかねない気がしています。
- `:lockvar` の代替として実際に使用することになるのは `:const` `か` `:final` のどちらかであって、`:const` `と` `:final` を両方ではないので、`か` のほうが適切だと思っています。

2021-04-30 05:32 UTC, tsuyoshicho commented on doc/vim9.jax
> +使用してください。
たしかにそうですね...。むずかしいけどそのままですかね。

2021-04-30 05:43 UTC, obcat commented on doc/vim9.jax
> +使用してください。
一旦このままにして、他の方の意見も聞いてみたいと思います。ご確認感謝です 🙏

2021-06-21 10:47 UTC, h-east commented
@obcat こちらをCloseして、 #912 を更新していただくということでOKですか？

2021-06-21 13:01 UTC, obcat commented
はい、そのようにしていただけると助かります🙏

2021-06-21 22:04 UTC, closed without merging