Update textprop.{txt,jax}
vim-jp/vimdoc-ja-working pull request #976
Opened 2021-11-20 12:02 UTC by kuuote

翻訳しました、よろしくお願いします。

2021-11-20 12:10 UTC, tsuyoshicho requested changes
見てみました

2021-11-20 12:10 UTC, tsuyoshicho commented on doc/textprop.jax
> +		{props}は次のフィールドを持つ辞書である:
```suggestion
		{props} は次のフィールドを持つ辞書である:
```

2021-11-20 12:10 UTC, tsuyoshicho commented on doc/textprop.jax
> +		第二引数はリストのリストで、各リストはテキストの始端と終端の
```suggestion
		第二引数はリストのリストで、各リストはテキストの開始と終了の
```
用語を統一

2021-11-20 12:10 UTC, tsuyoshicho commented on doc/textprop.jax
> +		される位置の直後を示す。
変更は不要かなとは思いますが...
意味としては付加される位置の直後はあっていますが、元文的には、(付加する)テキストの直後、なのでちょっとだけ悩みますね

2021-11-20 12:20 UTC, tsuyoshicho commented on doc/textprop.jax
> +		第二引数はリストのリストで、各リストはテキストの始端と終端の
下で「開始」、としているのでそれに合せ、またそこと対で終了としていますが....合せかたは色々ありそう

2021-11-20 13:30 UTC, kuuote commented on doc/textprop.jax
> +		{props}は次のフィールドを持つ辞書である:
下のlnum等に合わせて、ということなんでしょうが、他の箇所を見ると全部詰めているようなのでlnum等をそちらに合わせることにします

2021-11-20 13:34 UTC, tsuyoshicho commented on doc/textprop.jax
> +		{props}は次のフィールドを持つ辞書である:
最近追加される文面は `{xxx}` でも空白を付けてますが、全体と整合する方にあわせるでも大丈夫です(というかここが若干明確じゃないな....)

2021-11-20 13:36 UTC, kuuote commented on doc/textprop.jax
> +		される位置の直後を示す。
元の表現が砕けててちょっと分かりにくいかなと思って意訳してしまったんですが、ここは悩み所ですね

2021-11-20 13:44 UTC, tsuyoshicho approved these changes

2021-11-20 23:53 UTC, h-east commented on doc/textprop.jax
> +		第二引数はリストのリストで、各リストはテキストの開始と終了の位
基本的にはアラビア数字を使います。

```suggestion
		第2引数はリストのリストで、各リストはテキストの開始と終了の位
```

2021-11-21 04:33 UTC, kuuote commented on doc/textprop.jax
> +		第二引数はリストのリストで、各リストはテキストの開始と終了の位
直しました。

2021-11-22 09:45 UTC, k-takata approved these changes

2021-12-08 13:37 UTC, tsuyoshicho approved these changes
LGTM
新規の翻訳から {hoge} の前後空白やったほうがいいかな、とも思ったけど、他の量もあるしとりえあえずOK

2021-12-09 12:35 UTC, merged

2021-12-09 12:36 UTC, k-takata commented
thx