update en/pi_netrw.txt
vim-jp/vimdoc-ja-working pull request #989
Opened 2021-12-12 15:48 UTC by ryicoh

2021-12-12 23:20 UTC, tsuyoshicho requested changes
確認してみました。

2021-12-12 23:20 UTC, tsuyoshicho commented on en/pi_netrw.txt
> +           This change was done to allow for |netrw-cb| and |netrw-cB| maps.
ここのインデント調整を翻訳日本語版にも適用してよいと思います。

2021-12-12 23:20 UTC, tsuyoshicho commented on doc/pi_netrw.jax
> + 				(|netrw-handler| 参照).
```suggestion
				指定しているビューアがリモートURLをサポートす
				るかどうかを設定します。(|netrw-handler| 参照).
```
だと思います。

2021-12-12 23:20 UTC, tsuyoshicho commented on doc/pi_netrw.jax
> +				復元されないということです。
```suggestion
				(うっかり)変更された場合でも、それは以前の状態
				に復元されないということです。
```
くらいのほうがよさそう?
(ここはあまり自信ありません)

2021-12-12 23:20 UTC, tsuyoshicho commented on doc/pi_netrw.jax
> +				  および｜'cal'｜の設定値を意味します。
```suggestion
				  初期設定は、netrw を最後に開いたときの
				  |g:netrw_cursor| >= 5 または、netrw が最初に
				  実行されたときに有効だった |'cuc'| および
				  |'cal'| の設定値を意味します。
```
フォーマットがこれでいいかはありますが...、 | は半角です

2021-12-12 23:20 UTC, tsuyoshicho commented on doc/pi_netrw.jax
> +				（復元は必要に応じてのみ行われます）。
```suggestion
				しかし、一部のユーザーからスピードの問題がある
				と報告されています。したがって、このオプション
				をゼロに設定ことで netrw がクリップボードの保
				存と復元を行わないようにすることができます (復
				元は必要に応じてのみ行われます)。
```
フォーマット、および括弧は半角

2021-12-13 08:08 UTC, ryicoh commented on en/pi_netrw.txt
> +           This change was done to allow for |netrw-cb| and |netrw-cB| maps.
a3335b1
修正しました！

2021-12-13 08:13 UTC, ryicoh commented
レビューありがとうございます！
ユーザーとインデント修正しました。他の提案もコミットしました。

ユーザの方は、コメントしていただいてたのに気が付かず、forcecommitしちゃていました。

インデントはこちらです。
https://github.com/vim-jp/vimdoc-ja-working/pull/989#discussion_r767341315

2021-12-13 10:40 UTC, tsuyoshicho approved these changes
指摘箇所以外はLGTM

2021-12-13 10:40 UTC, tsuyoshicho commented on doc/pi_netrw.jax
> +				変更されないようにしようとします。
```suggestion
				デフォルトでnetrw はクリップボードの値が変更さ
				れないようにしようとします。
```
かな?

2021-12-14 04:22 UTC, ryicoh commented
レビューありがとうございます。
https://github.com/vim-jp/vimdoc-ja-working/pull/989/commits/6cce167511673d7794959f053f96db2114044537
提案していただいたのをコミットしたのち、
https://github.com/vim-jp/vimdoc-ja-working/pull/989/commits/65110ed49badb3f318e8b7b349292aea3b455411
[autofmt](https://github.com/vim-jp/autofmt) しました。

2022-01-15 04:21 UTC, tsuyoshicho commented
ping @k-takata san, @h-east san

2022-02-22 08:31 UTC, merged

2022-02-22 08:31 UTC, k-takata commented
thx